Components/CartSummaryViewComponent.cs
using BookStoreMorey.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreMorey.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Components/NavigationMenuViewComponent.cs
using BookStoreMorey.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BookStoreMorey.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {

        private IBookRepository repository;

        public NavigationMenuViewComponent (IBookRepository r)
        {
            repository = r;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

Views/Shared/BookSummary.cshtml
@model Book

<div class="card card-outline-light m-1 p-1" style="background-color: #913f0f;">
    <div class="bg-faded p-1">
        <h3>@Model.Title</h3>
        <p>Author: @Model.AuthorFName @Model.AuthorLName</p>
        <p>Publisher: @Model.Publisher</p>
        <p>ISBN: @Model.ISBN</p>
        <p>Classification: @Model.Classification</p>
        <p>Category: @Model.Category</p>
        <span class="badge badge-pill badge-light" style="float:right">
            <p>Price: $@Model.Price</p>
        </span>
        <p>Number of Pages: @Model.NumPages</p>
    </div>

    <form id="@Model.BookID" asp-page="/Buy" method="post">
        <input type="hidden" asp-for="BookID" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Title
            <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                Add to Cart
            </button>
        </span>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStoreMorey</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <script src="https://kit.fontawesome.com/b0ee4d56e2.js" crossorigin="anonymous"></script>
</head>
<body style="background-color: #913f0f;">
    <div class="bg-light text-black-50 p-2">
        <span class="navbar-brand ml-3">BOOK STORE</span>
        <div class="col-6 text-right">
            <vc:cart-summary />
        </div>
    </div>
        <div class="row m-1 p-1">
            <div class="col-3">
                <h1>Reasons To Read</h1>
                <ul class="list-group text-black-50">
                    <li class="list-group-item">Stress Relief</li>
                    <li class="list-group-item">Increase Cognitive Function</li>
                    <li class="list-group-item">Use Imagination</li>
                </ul>
                <br />
                <br />
                <vc:navigation-menu />
            </div>

            <div class="col-9" style="color:white;">
                @RenderBody()
            </div>
        </div>
</body>
<footer style="background-color:white;">
    <div class="text-center text-white-50">
        <span class="card-footer" style="color:black;">Morey Copyright 2021</span>
    </div>
</footer>
</html>